server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: https://easycloud-registry-service.herokuapp.com/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: easycloud-security
        uri: https://security-service-upc.herokuapp.com/
        predicates:
        - Path=/security/**
      - id: easycloud-pricing
        uri: http://easycloud-env.eba-6dy2ppey.us-east-1.elasticbeanstalk.com/
        predicates:
        - Path=/quote/**
      - id: easycloud-scaling
        uri: http://easycloudsca-env.eba-7mbw4wax.us-east-1.elasticbeanstalk.com/
        predicates:
        - Path=/scale/**
      - id: easycloud-visualization
        uri: http://easycloudvis-env.eba-ibhf7b3s.us-east-1.elasticbeanstalk.com/
        predicates:
        - Path=/visualize/**
