server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: https://easycloud-registry-service.herokuapp.com/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: easycloud-pricing
          uri: lb://easycloud-pricing
          predicates:
            - Path=/quote/**
        - id: easycloud-scaling
          uri: lb://easycloud-scaling
          predicates:
            - Path=/scale/**
        - id: easycloud-visualization
          uri: lb://easycloud-visualization
          predicates:
            - Path=/visualize/**
        - id: easycloud-security
            uri: lb://easycloud-security
            predicates:
              - Path=/security/**