server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: https://easycloud-registry-service.herokuapp.com/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: easycloud-security
            uri: https://security-service-upc.herokuapp.com/
            predicates:
              - Path=/security/**
#        - id: easycloud-pricing
#          uri:
#          predicates:
#            - Path=/quote/**
#        - id: easycloud-scaling
#          uri: lb://easycloud-scaling
#          predicates:
#            - Path=/scale/**
#        - id: easycloud-visualization
#          uri: lb://easycloud-visualization
#          predicates:
#            - Path=/visualize/**
